### ISSUE TITLE
Styling of group and device lists

### ISSUE THREAD

**Issue by mjs** [TheCacophonyProject/cacophony-browse#112]
On the Group and Device list screens the entire row is clickable (good) but this isn't obvious. I suggest:

- highlight the current row by changing the background color when the mouse hovers over it
- change the mouse cursor to indicate it's clickable

If this is done, do we need the arrow on the right?

**Comment by NickR49** [comment]
This is the first thing I noticed too coming into the app. I can make that change if it's okay . . .

**Comment by mjs** [comment]
@NickR49 we'd love your help with this but it's worth noting that we currently have a UX/UI expert creating new designs for much of the app. There is likely to be more significant changes to these pages coming.

You can see the parts of the redesign that have already been planned. These are represented by the issues labelled [UX/UI Improvement](https://github.com/TheCacophonyProject/cacophony-browse/issues?q=is%3Aissue+is%3Aopen+label%3A%22UX%2FUI+improvement%22). Each as links to mock ups. Changes for the admin screens haven't been finalised yet.

That said, it might be a while before we get to improving the group and device list screens so if you want to go ahead and make the small improvements listed on this issue, we will gladly accept your contribution.

**Comment by NickR49** [comment]
Wonderful thanks, it'll be a nice starter issue to start getting familiar with the codebase. I have made the change for the groups page, now I just need to work out how to add devices so that I can make the device page changes. I have a day job with deadlines like everyone else here I imagine so my contributions might be a little bit sporadic!

**Comment by mjs** [comment]
@NickR49 thanks very much for picking this up. I understand that contributions will be bursty and that's absolutely fine. We are grateful for whatever you can contribute.
