### ISSUE TITLE
Homepage - show something meaningful after the user registers/if there are no groups

### ISSUE THREAD

**Issue by saracoutinho** [TheCacophonyProject/cacophony-browse#142]
See https://xbn8fg.axshare.com/#id=bkicg7&p=home_-_first_run&view=default&g=1
(a [few tips](https://docs.google.com/document/d/1VEM0A3UmL0p4MctywCkBLk4lyh4IqejfK5JSIJlrW7E/edit) on how to use the prototype)

At the moment once a user registers there is no indication of what they should do next. We should provide them some guidance.

1. Have a blob of text with an explanation of what’s going on under the page header.

2. Provide two options: 
- Create a group (for users who are setting up their one devices)
   Link to the “Create group” popup in the Admin area.
- Join an existing group 
   Provide instructions on how to join an existing group. Display username so users can share it with group administrators.

**Comment by mjs** [comment]
This was done some time ago.
