### ISSUE TITLE
Recordings - have a textual description of the search criteria

### ISSUE THREAD

**Issue by saracoutinho** [TheCacophonyProject/cacophony-browse#144]
See https://xbn8fg.axshare.com/#id=hpb2y9&p=recordings_list&view=default&g=1
(a [few tips](https://docs.google.com/document/d/1VEM0A3UmL0p4MctywCkBLk4lyh4IqejfK5JSIJlrW7E/edit) on how to use the prototype)

![image](https://user-images.githubusercontent.com/5598943/54080821-7ece9c80-435d-11e9-8fa1-889f3e62e447.png)

Add a textual description of the search criteria on top of the search results. This will help users understand what they're currently looking at.

- Bold the keywords (e.g **all animals**) of the search criteria.
- I’d say only display the advanced search information if the user has changed any of the defaults (instead of saying “**all durations**”, don’t display anything).
- If the user changes the search criteria, the search textual description should change too to reflect this e.g “… and **tag types: possum, rat**.”

**Comment by mjs** [comment]
Done in #202
