### ISSUE TITLE
Recordings - move search fields to left side of screen

### ISSUE THREAD

**Issue by saracoutinho** [TheCacophonyProject/cacophony-browse#145]
See https://xbn8fg.axshare.com/#id=hpb2y9&p=recordings_list&view=default&g=1
(a [few tips](https://docs.google.com/document/d/1VEM0A3UmL0p4MctywCkBLk4lyh4IqejfK5JSIJlrW7E/edit) on how to use the prototype)

Move search filters to the left side of the screen and have form elements stacked.

**Mobile and tablet**
- Collapse the search on smaller screen sizes (smaller than large devices size https://getbootstrap.com/docs/4.3/layout/overview/#responsive-breakpoints).
- Toggle the search bar visibility by clicking on the search icon button on the left hand side. When the search bar is visible/expanded, the search icon changes to a close button. Clicking on the close button dismisses the search panel.

Nice to have: animate the search panel appearing/disappearing.

![gif of search panel on mobile](https://lh5.googleusercontent.com/_BVBDpYSw7gf4K6zo0NHb_sE7v3drFIIFYVluGokx-BhScehIW2MjM5hjUJ_2cHYseyixa6XUu359lUR8ajSbDsIdYDE1Zz_wuOGmCgAOI3ijnn8VugoNFiuJwmjQaQebVGr3ZfA)

**Comment by hardiesoft** [comment]
Can close?

**Comment by mjs** [comment]
Done in #202
