### ISSUE TITLE
Recordings - hide less commonly used filters under an "advanced search" toggle button

### ISSUE THREAD

**Issue by saracoutinho** [TheCacophonyProject/cacophony-browse#146]
See https://xbn8fg.axshare.com/#id=hpb2y9&p=recordings_list&view=default&g=1
(a [few tips](https://docs.google.com/document/d/1VEM0A3UmL0p4MctywCkBLk4lyh4IqejfK5JSIJlrW7E/edit) on how to use the prototype)

Move less commonly used filters to an advanced search area and hide them by default. The extra filters can be accessed by clicking on a “advanced search” button; this button toggles the visibility of the extra fields.

![Gif of advanced search](https://lh5.googleusercontent.com/KuBeo-dSkvsVJc4VmqVZ4pA8M8QQv-RrWkGmL7YCXtslb17y6MsoaChedVWN_M69MXpYWTFwHTVEcQFM4arFHT0L7Ksqq-ZM-ZlNGnytE0x2ZF4XqgKBb00XDkLvIzf9JDWFyUke)

**Comment by hardiesoft** [comment]
Can close?

**Comment by mjs** [comment]
Done in #202
