### ISSUE TITLE
Recordings - change behaviour of date fields

### ISSUE THREAD

**Issue by saracoutinho** [TheCacophonyProject/cacophony-browse#147]
See https://xbn8fg.axshare.com/#id=hpb2y9&p=recordings_list&view=default&g=1
(a [few tips](https://docs.google.com/document/d/1VEM0A3UmL0p4MctywCkBLk4lyh4IqejfK5JSIJlrW7E/edit) on how to use the prototype)

- Change the date field dropdown to have a set of predefined date ranges: last 24 hours, last 3 days, last 7 days, custom.
- Selecting “custom range” reveals two extra date fields: “from” and “to” (and they should work as they currently do). Changing the dropdown selection from ‘custom range’ to something else should hide the two extra date fields.

![gif of date fields](https://lh3.googleusercontent.com/bt3ZglOIHCUQ0hdkJQGKGmBx_JtZabUWoyOwqnLZCU6U8xRXcW9Q2O5MDJZQXyHtcPMQ2IT1o39hcp1-lmS4MRgcGpjRXXRaobnj2vi-zJI0qAN9iftz0bIKb2GT9UY536aJwxRf)

**Comment by hardiesoft** [comment]
Can close?

**Comment by mjs** [comment]
Done in #202
