### ISSUE TITLE
Delete popup shows on automatic suggestion and Confirm is unclickable

### ISSUE THREAD

**Issue by gferraro** [TheCacophonyProject/cacophony-browse#164]
When tagging tracks with a automatic tag the Delete Tag popup shows when you can't delete it.
Also the popup to confirm automatic tag seems to flicker in and out and be un clickable. I think this only occurs on the second or so track with a automatic tag.

Happens for: https://browse-test.cacophony.org.nz/recording/154871

This happens on Ubuntu google chrome Version 74.0.3729.131 (Official Build) (64-bit)

**Comment by mjs** [comment]
This is a duplicate of #180.
