### ISSUE TITLE
Add Tag To Video allows ok to close popup with invalid data

### ISSUE THREAD

**Issue by gferraro** [TheCacophonyProject/cacophony-browse#174]
If you enter invalid data, and click ok. It doesn't add the track and closes the modal popup showing no message.
Clicking the add tag to video button again shows the modal popup with previous values and the error message "Invalid form." 
Updating the invalid values works but when you click add tag to video button again the "Invalid Form" message is still there

**Comment by mjs** [comment]
This is no longer relevant
