### ISSUE TITLE
Other popup doesn't show on 2nd recording

### ISSUE THREAD

**Issue by fencesitter** [TheCacophonyProject/cacophony-browse#184]
Using Chrome on Windows. When you view a video you can press the other (+) button and  a popup allows you to chose another tag and comment. If you click the previous (<) button then when the next recording loads the popup won't (pop up) when you press the other button. Refreshing the screen fixes this.

**Comment by mjs** [comment]
Thanks. This sounds like the same thing Grant was seeing.
