### ISSUE TITLE
Video selection preference is not applied to initial query

### ISSUE THREAD

**Issue by mjs** [TheCacophonyProject/cacophony-browse#242]
The preferred recording type is now remembered but is not honoured when first visiting the query page (you still end up with all recording types). This is a tad confusing.

**Comment by hardiesoft** [comment]
I don't seem to be able to replicate this - what are the exact steps you're taking to see this behaviour?

**Comment by hardiesoft** [comment]
Never mind, I see what you mean now, will take a look
