### ISSUE TITLE
Pagination controls don't appear on a small screen

### ISSUE THREAD

**Issue by mjs** [TheCacophonyProject/cacophony-browse#250]
On a standard ipad, the pagination controls don't appear at the bottom of the search results page.

**Comment by chrised123** [comment]
Hey @mjs,
can it take this as my first issue. I am looking at your projects and love to contribute.

**Comment by clare** [comment]
Hi Sanjith, 

Thanks so much for your interest in the project!

Unfortunately, @mjs is busy with other things now but I am happy to guide you through this.  

As you see this is an old issue and someone might have fixed it by now, but I don't have an Ipad to test it with.   To test the problem you will need to login into https://browse-test.cacophony.org.nz.   Then I can add you to a group so you can see recordings.   Then go to https://browse.cacophony.org.nz/recordings and search for all recordings and see if you can see the pagination.  

Thanks
Clare

**Comment by chrised123** [comment]
Hi @clare Thank you for the reply. I've created an account and my username is - **chrised132**
Feel free to let me know if there are other pressing issues as well.

**Comment by clare** [comment]
Done now so you should hopefully be able to see some recordings.   They recording are all quite old thought so if you don't see anything make sure you don't have "last 30 days" checked.     

Other issues you might be interested in are https://github.com/TheCacophonyProject/cacophony-browse/issues/251, 
https://github.com/TheCacophonyProject/cacophony-browse/issues/241, https://github.com/TheCacophonyProject/cacophony-browse/issues/212,  

Please let me know if you want clarification, as I know all are bugs are poorly spec'd.   

Also if you find this is no longer an issue please close the bug.  

Finally if you are looking for a bigger task then this would be super useful to get done: https://github.com/TheCacophonyProject/cacophony-browse/issues/288'

Thanks so much, 
Clare

**Comment by chrised123** [comment]
Hi @clare,

It seems like the pagination is visible for mobile devices. Although some space might be needed. 
<img width="436" alt="Screenshot 2020-07-29 at 10 16 53 AM" src="https://user-images.githubusercontent.com/8319089/88748990-f2f12680-d184-11ea-91a5-ae5d01426c97.png">

I will take a look at the above mentioned issues as well.

**Comment by clare** [comment]
Yes.   I'm not sure it works on an actual Ipad though.   Part of the problem might be safari.  :)

**Comment by chrised123** [comment]
Oh Ok. Let me check on my iPad.

**Comment by chrised123** [comment]
Got the issue. Will work on this issue first then.

![Uploading 89127270...]()

**Comment by chrised123** [comment]
@clare I've created a pull request. Please take a look. It has fixed the issue on IPads and visually similar in other views as well.
