### ISSUE TITLE
Export failed

### ISSUE THREAD

**Issue by fencesitter** [TheCacophonyProject/cacophony-browse#270]
I tried to export some audio recordings and got this message:
{"messages":["Failed to verify JWT."]}

This is the URL:
https://api.cacophony.org.nz/api/v1/recordings/report?where=%7B%22DeviceId%22%3A%5B735%2C767%2C746%2C750%2C751%2C752%2C788%2C808%2C800%2C804%2C812%2C813%2C814%2C816%2C817%2C818%2C819%2C820%2C821%2C823%2C826%2C828%2C541%2C542%2C560%2C543%2C546%2C568%2C720%2C729%2C544%2C545%2C535%2C536%2C548%2C721%2C537%2C549%2C538%2C539%2C540%2C550%5D%7D&limit=100000&offset=0&tagMode=any&jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ODgsIl90eXBlIjoidXNlciIsImlhdCI6MTU3NjIwODAxMCwiZXhwIjoxNTc2MjA4MDcwfQ.yXr_k9B4C-ediwHehjIh091V4XjE5x9eakURumvtwvE

Using Chrome on Windows with my fencesitter account

**Comment by mjs** [comment]
I can reproduce this. Cam and I should have a fix soon.

**Comment by mjs** [comment]
The underlying problem is actually in the API server. See https://trello.com/c/KYnPlpYq/287-query-for-csv-export-is-slow

**Comment by mjs** [comment]
Initial workaround here: https://github.com/TheCacophonyProject/cacophony-api/pull/291

**Comment by mjs** [comment]
Closing as this work is now covered elsewhere.
