### ISSUE TITLE
Search results don't load when going back from a recording

### ISSUE THREAD

**Issue by fencesitter** [TheCacophonyProject/cacophony-browse#272]
If you view a list of search results, watch a video or listen to a recording and then press the back button, the search results page is stuck loading. This seems to be a new issue and is a happening consistently across devices.
![image](https://user-images.githubusercontent.com/19642961/71026614-7cac3080-216e-11ea-9138-5d0ebf5b58d9.png)

To replicate:
- visit the home screen
- click on the 331 Ashgrove group
- click on a recording
- click the browser back button
- recordings will be missing

**Comment by mjs** [comment]
I've had a initial look at this and it seems that the date range is missing from the recoridng URL when the back button is used. If a date range is selected and Search is clicked then results appeared.

**Comment by gferraro** [comment]
Fixed
