### ISSUE TITLE
Filter by Custom Date Range shows results present but no display of rows of recordings

### ISSUE THREAD

**Issue by auphofBSF** [TheCacophonyProject/cacophony-browse#280]
# Issue's - possible bugs
1) Custom Date range dates are not being displayed fully
2) No Records are displayed but result count shows filter returned results

# Notes
The issue 2 only materializes after a prior selection of 2nd or more additional pages of recordings (default is 100 recordings per page) and then doing a custom date range lookup. I believe the results returned are not requiring additional pages but the browser is still trying to display the prior chosen page of results and not the first page. Possible other filters may do the same

![CP-20W04d5-RecordingsCustomDateRangeIssues](https://user-images.githubusercontent.com/11743864/73028007-7ad63b00-3e99-11ea-95b6-abfea680ab22.gif)

# Expected Behaviour
1) Dates display  dd/mm/yyyy or  localization preference ie yyyy/mm/dd
2) Page selection get reset so not effect new filter return results and there display, records are displayed

## Versions
from `chrome://version`

Google Chrome | 79.0.3945.130 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1903 (Build 18362.535)
JavaScript | V8 7.9.317.33
Flash | 32.0.0.321 C:\Users\BSFau\AppData\Local\Google\Chrome\User Data\PepperFlash\32.0.0.321\pepflashplayer.dll
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Command Line | "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --profile-directory="Profile 1" --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox
Executable Path | C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Profile Path | C:\Users\\ .....\AppData\Local\Google\Chrome\User Data\Profile 1

**Comment by saracoutinho** [comment]
@auphofBSF  What browser, browser version and OS are you using?

**Comment by auphofBSF** [comment]
> @auphofBSF What browser, browser version and OS are you using?

Thanks @saracoutinho ,I should have included that, now added

**Comment by mjs** [comment]
I think what is happening here is that when the search results are on page N (where N is greater than 1) and the search criteria are then narrowed so there are no longer N pages, the search results come up empty.

Steps to replicate (somewhat overkill but will definitely do it):

- do a search that returns a lot of results (e.g. last 90 days)
- change to 10 results per page
- click on the "last page" button
- change the date range to "Last 24 hours", so that far fewer results are returned, and click Search
- no search results are shown

**Comment by auphofBSF** [comment]
> I think what is happening here is that when the search results are on page N (where N is greater than 1) and the search criteria are then narrowed so there are no longer N pages, the search results come up empty.
> 
> Steps to replicate (somewhat overkill but will definitely do it):
> 
> * do a search that returns a lot of results (e.g. last 90 days)
> * change to 10 results per page
> * click on the "last page" button
> * change the date range to "Last 24 hours", so that far fewer results are returned, and click Search
> * no search results are shown

Without even limiting to 10 results per page. the following simpler case will definitely show the error
> * do a search that returns a lot of results (e.g. last 90 days)
>* go to 2nd page
> * change the date range to "Last 24 hours", so that far fewer results are returned, and click Search
> * no search results are shown

**Comment by mjs** [comment]
@hardiesoft has fixed this in #290. This fix has merged today and will be deployed to test on Monday, and prod the following week.
