### ISSUE TITLE
Export not working

### ISSUE THREAD

**Issue by fencesitter** [TheCacophonyProject/cacophony-browse#289]
When I try to export over 30, 90 days, or all time I get this error:
{"messages":["Failed to verify JWT."]}

https://api.cacophony.org.nz/api/v1/recordings/report?where=%7B%22recordingDateTime%22%3A%7B%22%24lt%22%3A%222020-02-19%2012%3A53%3A28%22%2C%22%24gt%22%3A%222020-01-20%2012%3A53%3A28%22%7D%2C%22duration%22%3A%7B%22%24gte%22%3A%220%22%7D%2C%22DeviceId%22%3A%5B567%5D%7D&tagMode=any&jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ODgsIl90eXBlIjoidXNlciIsImlhdCI6MTU4MjA2OTg0NywiZXhwIjoxNTgyMDY5OTA3fQ.VIQ2IOKkpyaHEWnz3A05NWHChedVHlvlx-53uL8sg8A&offset=0&limit=100000

Using Chrome on an iPad - it was successfully exporting earlier today.

**Comment by fencesitter** [comment]
Also a failing on Chrome on Windows when requesting over all time. Note the 30 day query did work.

**Comment by hardiesoft** [comment]
Closed by https://github.com/TheCacophonyProject/cacophony-api/pull/308
