### ISSUE TITLE
Improve error message overlays

### ISSUE THREAD

**Issue by clare** [TheCacophonyProject/cacophony-browse#82]
1.   Need to improve the layout (CSS) for the error message so they look nicish
2.  Split uses of error message between two classes:
  a.  Actual error messages that need to stay visible until dismissed
  b.  Warming messages that appear for a while and then disappear.

**Comment by mjs** [comment]
Example of current look:

![image](https://user-images.githubusercontent.com/14993/47186327-b4fa8800-d38c-11e8-9a0c-12aea5a229d8.png)

**Comment by clare** [comment]
Done.   Although feel free to make better.
